name: Maven Build CI for Pull requests

on:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout from GitHub
        uses: actions/checkout@v2

      - name: Setup Java env
        uses: actions/setup-java@v2.1.0
        with:
          java-version: '8'
          distribution: 'zulu'
          check-latest: true

      - name: Maven build
        run:
            mvn -B -V clean install
